[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "solid-principles"
version = "0.1.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]